OLED_ENABLE = yes
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGB_MATRIX_ENABLE = no     # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
CONVERT_TO = liatris	   # The micro-controller I'm using
LTO_ENABLE = no			   # This fixes split board getting bogged
WPM_ENABLE = yes
WPM_SAMPLE_SECONDS = 10
SPLIT_TRANSPORT = yes
